from app.schemas.movie import Movie, Genre

# Offline fallback used only when TMDB credentials/network are unavailable.
SEED_MOVIES = [
    Movie(id=27205,title="Inception",original_title="Inception",overview="A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.",release_date="2010-07-16",year=2010,rating=8.8,vote_count=2500000,popularity=95,poster_url=None,backdrop_url=None,genres=[Genre(id=878,name="Science Fiction"),Genre(id=28,name="Action"),Genre(id=53,name="Thriller")],cast=[],director=None,runtime=148,trailer_url=None,tmdb_url="https://www.themoviedb.org/movie/27205"),
    Movie(id=157336,title="Interstellar",original_title="Interstellar",overview="Explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",release_date="2014-11-07",year=2014,rating=8.7,vote_count=2100000,popularity=91,poster_url=None,backdrop_url=None,genres=[Genre(id=878,name="Science Fiction"),Genre(id=18,name="Drama"),Genre(id=12,name="Adventure")],cast=[],director=None,runtime=169,trailer_url=None,tmdb_url="https://www.themoviedb.org/movie/157336"),
    Movie(id=155,title="The Dark Knight",original_title="The Dark Knight",overview="A masked vigilante faces a criminal mastermind who plunges Gotham into chaos.",release_date="2008-07-16",year=2008,rating=9.0,vote_count=3000000,popularity=89,poster_url=None,backdrop_url=None,genres=[Genre(id=28,name="Action"),Genre(id=80,name="Crime"),Genre(id=18,name="Drama")],cast=[],director=None,runtime=152,trailer_url=None,tmdb_url="https://www.themoviedb.org/movie/155"),
    Movie(id=603,title="The Matrix",original_title="The Matrix",overview="A computer hacker discovers that reality is a simulation and joins a rebellion.",release_date="1999-03-30",year=1999,rating=8.7,vote_count=2000000,popularity=85,poster_url=None,backdrop_url=None,genres=[Genre(id=878,name="Science Fiction"),Genre(id=28,name="Action")],cast=[],director=None,runtime=136,trailer_url=None,tmdb_url="https://www.themoviedb.org/movie/603"),
]
